name: Node.js CI with PR Comment

on:
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run tests and capture output
        run: |
          mkdir -p test_results
          yarn run test > test_results/results.txt 2>&1

      - name: Post PR Comment with Test Results
        uses: actions/github-script@v5
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const path = 'test_results/results.txt';
            const testResults = fs.readFileSync(path, { encoding: 'utf8' });
            const commentBody = `🚀 Test Results:\n\`\`\`\n${testResults}\n\`\`\``;
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: commentBody
            });

      - name: Archive test results
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            test_results/
